# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27a981aab050d20d3ad86244c0f768969064308c4e562f3b3ffba1d6e1fc58b293f481c0f7f738777c2a74df623ff92170d0c33589c90ae124c2cf3e49921f4

test:
  secret_key_base: 49ecf9cf98a6cd567d0bba56dc6acdf7b1ecbbbeba315471b158634778f09458ae2be2a473931ecb2110ba4838fff9e17659029947247f04cf8c9a89d2df24a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
